### PR TITLE
Fix control cable disconnects via backspace

### PR DESCRIPTION
**Pull request by asmw**
This will conflict with my 'right-click-to-disconnect' changes.

If both changes are acceptable, I will take care of that

### CODE REVIEW

**Comment by awwbees** [comment]
can you further describe which issues this fixes? I want to be able to test and see.

**Comment by asmw** [comment]
> can you further describe which issues this fixes? I want to be able to test and see.

Ah sorry, I thought this was a known issue.

I cannot disconnect connections from a midicontroller button by picking it up and pressing backspace.
image

The ONLY way I can remove a midicontroller connection is by clicking the 'x' in the list or in the individual connection panel.
image

**Comment by awwbees** [comment]
I'm gonna have to come back to this and do a little more work before merging. with this functionality, it puts the midicontroller into a weird state where the cable is disconnected, but the control mapping entry is still hanging around. I think the correct fix will be to make deleting the cable fully equivalent to hitting the "x" button

**Comment by asmw** [comment]
Ah right, didn't see that, sorry

**Comment by awwbees** [comment]
looks good! sorry that it took me so long to merge this one, github's diff was making the change look much more significant than it actually was.

**Pull request merged**
