### PR TITLE
Port to CMake; Port to Juce 6.1.1

### PR DESCRIPTION
**Pull request by baconpaul**
This commit is an initial port to CMkae/Juce 6.1.1 for Bespoke.
It changes the build procedure on all platforms.

The build procedure on linux mac and win post this commit is

```
git clone (argument)
cd BespokeSynth
git submodule update --init --recursive
cmake -Bignore/build
cmake --build ignore/build
```

### CODE REVIEW

**Comment by selenologist** [comment]
Hi, @baconpaul asked me to test this on Arch - just leaving a note for anyone else who tries this out: the hardcoded libusb path on line 427 of `CMakeLists.txt` https://github.com/baconpaul/BespokeSynth/blob/port-to-cmake/CMakeLists.txt#L427 won't work.

Until there's a proper way for cmake to find this as per the comment, replacing the path with `/usr/lib/libusb-1.0.so.0` there will get it to build.

**Comment by baconpaul** [comment]
Yeah lemme dig on that some too and any feedback welcome. It’s the only thing I couldn’t auto detect :(

**Comment by baconpaul** [comment]
Oh you know I bet it’s because I don’t have libusb dev properly configured in my vm - let me try and fix that before a merge

**Comment by dromer** [comment]
Totally works for me on Debian11. Thnx for the work @baconpaul !
(I guess if you stare at JUCE and cmake long enough things just happen on autopilot ;) )

Btw, run it from the root with `./ignore/build/BespokeSynth_artefacts/Release/BespokeSynth` (otherwise it doesn't find any assets)

**Comment by dromer** [comment]
VST scanning needs some work, it no longer sees anything in my `/usr/lib/vst`, however `/usr/lib/vst3` does work.

Python scripting works.

**Comment by baconpaul** [comment]
Oh right I didn’t include vst2 since this is free software - let me figure out how that could work

**Comment by baconpaul** [comment]
OK folks I did a force push that does a couple of things

1. Use find_library properly to find usb on linux. You probably need `libusb-1.0.0-dev` package installed 
2. Add back VST2 support. Since VST2 means you get a non-redistributable binary it is off by default but you can enable it with `-DBESPOKE_VST2_SDK_LOCATION=(path)` when you run your cmake

**Comment by baconpaul** [comment]
and another force push to fix that resource thing @dromer and a windows user reported.

**Comment by dromer** [comment]
@baconpaul is that also the case for vst2 hosting? this was always enabled by default, but I didn't know that good 'ol steinberg is even killing off hosts like this ..

There was no vst2sdk needed for getting hosting to work in Bespoke before, btw.

Edit: just setting `JUCE_PLUGINHOST_VST=1` indeed fails to build. Can't we just use vestige.h for this? :#
(I'm kind of confused that both current master and @KottV 's juce6.0 branch build vst2 hosting just fine)

**Comment by baconpaul** [comment]
The juce code is pretty clear @dromer 

```
/** Config: JUCE_PLUGINHOST_VST
    Enables the VST audio plugin hosting classes. You will need to have the VST2 SDK files in your header search paths. You can obtain the VST2 SDK files from on older version of the VST3 SDK.

    @see VSTPluginFormat, VST3PluginFormat, AudioPluginFormat, AudioPluginFormatManager, JUCE_PLUGINHOST_AU, JUCE_PLUGINHOST_VST3, JUCE_PLUGINHOST_LADSPA
*/
#ifndef JUCE_PLUGINHOST_VST
 #define JUCE_PLUGINHOST_VST 0
#endif
```

**Comment by dromer** [comment]
@baconpaul ok but I'm still confused as to how we had VST2 hosting before. And on @KottV 's 6.0.8 branch: https://github.com/KottV/BespokeSynth/tree/juce6

There are no headers anywhere, yet builds from these just work™
(end yes, I'm way too lazy to go trace the code for how this was done. I let that to the experts :#)

**Comment by baconpaul** [comment]
well the juicer file points at the VST2 SDK in out of source locations. Presume you fixed those and built.

Anyway it works still so you can do the same now.

**Comment by dromer** [comment]
Oh dear I'm an idiot, indeed the automagic of Projucer used some setting I configured ages ago that pointed to a dir that had VST2SDK .. and I didn't realize that this is why I had this capability :D

Sorry for the noise. Glad to have this more explicit now, sure!

However this means that the current binaries being distributed by @awwbees are illegal, since they have vst2 hosting enabled I believe. Or do you have a valid license to do this, since you started the project so long ago @awwbees ?
(this does make it a lot more tricky to have automated builds for distribution etc.)

**Comment by baconpaul** [comment]
Illegal is a very strong word. But depending on how it is licensed there may be a gpl3 problem sure.

**Comment by baconpaul** [comment]
And automated builds are easy still. There’s no technical question here just a license one.

**Comment by biomassa** [comment]
this builds on macos Big Sur / intel, "trashcan" macpro (late 2013) without any issues (I have XCode installed).
the issue with microphone input request triggering is also fixed, now input node is usable on mac.

many thanks go to @baconpaul

**Comment by baconpaul** [comment]
Just realized lfo.cpp isn’t compiled here. Want to check for other coo files I may have missed tomorrow

**Comment by jayanderson** [comment]
I gave this a try and it seemed to build successfully, but wouldn't start:

```
$ ./ignore/build/BespokeSynth_artefacts/Release/BespokeSynth 
Shader shader/vert error:

Shader shader/vert error:

Could not init nanovg.
Could not init font bounds nanovg.
Shader shader/vert error:

Killed
```

OS information:
```
$ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"
```

**Comment by dromer** [comment]
> And automated builds are easy still. There’s no technical question here just a license one.

There is if you want to retreive the sdk in those builds.
Could be a curl to the archive.org page of course, but this is a bit shady territory.

If there is indeed a valid license available, then we could do it like this perhaps

**Comment by baconpaul** [comment]
> I gave this a try and it seemed to build successfully, but wouldn't start:
> 
> ```
> $ ./ignore/build/BespokeSynth_artefacts/Release/BespokeSynth 
> Shader shader/vert error:
> 
> Shader shader/vert error:
> 
> Could not init nanovg.
> Could not init font bounds nanovg.
> Shader shader/vert error:
> 
> Killed
> ```
> 
> OS information:
> 
> ```
> $ cat /etc/lsb-release
> DISTRIB_ID=Pop
> DISTRIB_RELEASE=21.04
> DISTRIB_CODENAME=hirsute
> DISTRIB_DESCRIPTION="Pop!_OS 21.04"
> ```

Does bespoke work for you on that system if build with projucer?

**Comment by dromer** [comment]
@baconpaul can I ask why you keep force-pushing changes? We can just squash commits in the end to keep history clean, but it's interesting to see what your changes are in this PR.

**Comment by baconpaul** [comment]
> @baconpaul can I ask why you keep force-pushing changes? We can just squash commits in the end to keep history clean, but it's interesting to see what your changes are in this PR.

Habit for minor changes really. I’ll push diffs if there are more changes

**Comment by dromer** [comment]
Yeah I usually do force pushes if I'm on a relatively private branch and I'm just fixing typos or stupid mistakes :#

**Comment by baconpaul** [comment]
(the one this morning was rebasing this to master though so that did have to be a force)

**Comment by dromer** [comment]
So far the build process of this branch is super smooth for me. 6.1.1 seems to be quite stable too and I'm having a lot of fun using it!

Lets see if @awwbees can try this out asap, I think it'll give some quality of life improvements for sure.

**Comment by awwbees** [comment]
sweet, yeah, if this is good to go, I will find some time to look at it today. thank y'all so much!!

**Comment by baconpaul** [comment]
@awwbees i think it is. There’s still some resource location things which I’m fuzzy in though so a test that I didn’t explode it would help. 

But if we get this into main then we can chip away at those things. Like I kinda agree with #117 and could write a cmake rule to put the resources in the bundle and a bit of objective c to find the path once it’s merged if you agree with that path forward. Etc

**Comment by baconpaul** [comment]
Oh this also resolves  #116 as @biomassa confirmed last night

**Comment by awwbees** [comment]
let's do it 💥

**Pull request merged**
