### PR TITLE
Amplifier: don't go over the number of channels in the output

### PR DESCRIPTION
**Pull request by djdeath**

### CODE REVIEW

**Comment by djdeath** [comment]
Still seeing the issue reported on https://github.com/awwbees/BespokeSynth/commit/684afa5ac669877e8a4005f767c3454f0de3eed0

**Comment by awwbees** [comment]
I'm not seeing the issue after my 2c32588a7bb00a30aa415deb150d14d8503aabe9 change, can you provide steps to reproduce it? The `SyncBuffers()` call should be keeping `GetBuffer()->NumActiveChannels()` and `out->NumActiveChannels()` in sync.

**Comment by djdeath** [comment]
Sorry I can't remember how that happened, will update if that happens again.

**Comment by awwbees** [comment]
I have never encountered this issue, and it's now old, so I'll close this.

**Pull request closed without merging**
