### PR TITLE
Upgrade vendored JUCE to 7.0.6

### PR DESCRIPTION
**Pull request by dvzrv**
There are still a few deprecations (see warnings during build) to take care of afterwards, but they are a bit above my C++ knowledge/ knowledge of this project and it would be better if they were cleaned up by a more proficient developer afterwards.

### CODE REVIEW

**Comment by dvzrv** [comment]
I've added the change to the function signature to the Arch Linux distribution package to be able to build against juce 7.0.5, which we ship.

**Comment by KottV** [comment]
JUCE 7.0.3 - 7.0.5 has thread managing regression https://forum.juce.com/t/bug-serious-problem-with-highresolutiontimer-since-juce-7-0-3/55321

It doesn't seem to affect Bespoke, but I'm not sure)

Also LV2 hosting is partially broken in 7.0.5 https://github.com/juce-framework/JUCE/issues/1236 (fixed in develop)

**Comment by dvzrv** [comment]
> JUCE 7.0.3 - 7.0.5 has thread managing regression https://forum.juce.com/t/bug-serious-problem-with-highresolutiontimer-since-juce-7-0-3/55321
> 
> It doesn't seem to affect Bespoke, but I'm not sure)
> 
> Also LV2 hosting is partially broken in 7.0.5 [juce-framework/JUCE#1236](https://github.com/juce-framework/JUCE/issues/1236) (fixed in develop)

Guess one could wait to have a 7.0.6 materialize before merging this change.

**Comment by dvzrv** [comment]
Updated to 7.0.6

**Comment by yurivict** [comment]
Patches don't apply to the latest 'main' branch.

**Comment by dvzrv** [comment]
> Patches don't apply to the latest 'main' branch.

what do you mean by that? the patches are based on the latest commit on main, which is currently https://github.com/BespokeSynth/BespokeSynth/commit/71134ce432dd15ae773cd49ac7c6e436d37e8a46

As to the failing checks: I don't see any logs as they are in some private pipeline(?), so that's probably something @awwbees or someone else has to look into. Looking at the nightly pipeline, there seems to be some unrelated issue though:

https://build.opensuse.org/package/live_build_log/home:bespokesynth/bespokesynth-nightly/Fedora_37/x86_64
https://build.opensuse.org/package/live_build_log/home:bespokesynth/bespokesynth-nightly/Fedora_38/x86_64

**Comment by KottV** [comment]
> As to the failing checks: I don't see any logs as they are in some private pipeline(?), so that's probably something @awwbees or someone else has to look into. Looking at the nightly pipeline, there seems to be some unrelated issue though:
> 
> https://build.opensuse.org/package/live_build_log/home:bespokesynth/bespokesynth-nightly/Fedora_37/x86_64 https://build.opensuse.org/package/live_build_log/home:bespokesynth/bespokesynth-nightly/Fedora_38/x86_64

OBS pipelines (especially which are not openSUSE builds) should be excluded from PR check.

**Comment by KottV** [comment]
Tested on my system (openSUSE tW), works fine.

**Comment by yurivict** [comment]
juce-7.0.7 is out.
Is BespokeSynth compatible with it?

**Comment by KottV** [comment]
> juce-7.0.7 is out. Is BespokeSynth compatible with it?

there is no breaking changes in this release, so it should be compatible

**Comment by awwbees** [comment]
thank you! I believe this update might fix #1383, which I've been struggling with (via this juce fix https://github.com/juce-framework/JUCE/commit/455c865d372a138eec4de64d38ce8074d542190e)

**Pull request merged**
