### PR TITLE
push2: Lib-ify

### PR DESCRIPTION
**Pull request by mvf**
- Add libs/CMakeLists.txt
- Move push2 to libs
- Hide libusb dependency from rest of codebase
- Linux/BSD: Fix header mismatch (i.e. including our libusb.h but
  linking against system libusb)
- Use system libusb on MinGW

### CODE REVIEW

**Comment by baconpaul** [comment]
Nice!

**Comment by awwbees** [comment]
oh interesting, cool thanks! so I'm guessing this makes it easier to build for folks who don't care about push 2 support? (which is the vast majority of users)

**Comment by awwbees** [comment]
it's definitely interesting to know about this technique for other obscure dependences like SpaceMouseControl (of which I will probably be the only client)

**Comment by mvf** [comment]
> so I'm guessing this makes it easier to build for folks who don't care about push 2 support?

This was just the groundwork, #322 makes Push support optional with graceful fallback on missing `libusb`.

**Pull request merged**
