### PR TITLE
Allow the scrollwheel to adjust the Q slider while hovering over a dot in the `eq` module.

### PR DESCRIPTION
**Pull request by NoxyNixie**
You can also adjust the increment by holding shift or control/command for faster and slower respectively.

### CODE REVIEW

**Comment by PowerUser64** [comment]
The only things I would change about this are currently, holding shift while scrolling changes the q in larger increments rather than smaller increments, which is inconsistent with the rest of bespoke. Additionally, adjustments should probably be larger for higher values and lower for small values, right now it's linear. Other than that, things work as expected!

**Comment by NoxyNixie** [comment]
> The only things I would change about this are currently, holding shift while scrolling changes the q in larger increments rather than smaller increments, which is inconsistent with the rest of bespoke. 

Owh looks like I reversed that logic by accident.

> Additionally, adjustments should probably be larger for higher values and lower for small values, right now it's linear. Other than that, things work as expected!

Ah yeah, non linear does feel better. I tweaked some values and personally think it feels good now but what is your opinion?

**Comment by PowerUser64** [comment]
Feels great! If I could change one other thing, it would be to have pressing backslash on a point could reset its values. Other than that, scrolling feels great! Shift-scrolling works as expected, and changing the max/min values produces expected results as well.

**Comment by NoxyNixie** [comment]
The backslash key now reset to original and also added `[` and `]` to behave similar to sliders where they halve and double.

**Pull request merged**
