### PR TITLE
Fix trailing newlines, module folder structure

### PR DESCRIPTION
**Pull request by ckiee**
Configured CMake to generate `compile_commands.json` for clangd and messed around in the shell for an ~hour to put stuff in folders.

### CODE REVIEW

**Comment by awwbees** [comment]
we unfortunately had two in-flights PRs that touched a bunch of the same files, so this one will need to have its conflicts resolved before merging

**Comment by ckiee** [comment]
oh how so very merry (:

**Comment by awwbees** [comment]
closing this until merge issues are resolved. bad timing on touching all the files, sorry!

**Comment by ckiee** [comment]
mhm! all good (:

**Pull request closed without merging**
