### PR TITLE
Fix python3 Linux linking flags

### PR DESCRIPTION
**Pull request by KottV**
Hi,

It works for openSUSE, Ubuntu 20.04 and Debian 11 (python3.9)

### CODE REVIEW

**Comment by KottV** [comment]
Ohhh, it seems it works only for python >= 3.8 and doesn't for 3.6 :(

**Comment by awwbees** [comment]
ah, that is fine, I think python 3.8 will be my minimum supported version anyway. that mirrors the requirements on windows and mac. I inadvertently only have 3.6 installed on my linux machine, I need to update.

**Comment by awwbees** [comment]
I'm working through some issues getting my machine configured correctly for python3.8, I will merge this PR once I resolve that and can test it

**Comment by KottV** [comment]
no problem, i've a patch in my build repo, with condition for 3.6 and 3.8 python versions

**Comment by awwbees** [comment]
ah... should I merge this change, or do you have another change that works better? I just updated to ubuntu 20.04 (which was the best way I could see to get python 3.8) and tested this change, it worked for me.

**Comment by KottV** [comment]
yes, it's a proper solution (i'm sure as hell!)

**Comment by KottV** [comment]
Also added JACK Client name

**Comment by awwbees** [comment]
thanks!

**Pull request merged**
