### PR TITLE
Windows 32-bit: Restore support, fix crash on startup

### PR DESCRIPTION
**Pull request by mvf**
32-bit virtual address space is only 2GiB by default. Bespoke allocates
a ~330 MiB chunk on startup, which was failing with `bad_alloc`. So let
the linker set the `IMAGE_FILE_LARGE_ADDRESS_AWARE` flag, extending VA
space to up to 3 GiB on 32-bit systems (when booted with `/3G`) and the
full 4 GiB on 64-bit systems.

### CODE REVIEW

**Comment by baconpaul** [comment]
I figured just explicitly don’t support 32 bit was a better strategy. Fine either way of course but is there a use case for a 32 bit daw that makes sense?

**Comment by mvf** [comment]
> I figured just explicitly don’t support 32 bit was a better strategy.

The change that jettisoned 32-bit (on Windows only) didn't give any technical reason for doing so. 32-bit is no real extra effort, so I see no rush to drop it just yet. The use case for 32-bit Windows in particular is legacy VSTs. We also have Raspberry Pi users with 32-bit userland.

**Comment by baconpaul** [comment]
64 bit windows will load 32 bit vsts. Like I said I’m not bothered. I just wanted to avoid people having bad self builds since 32 bit win daw just isn’t useful won’t scan most vsts may not link and load python etc… so try and make the build you probably don’t want show an error was my thinking.

**Comment by mvf** [comment]
> 64 bit windows will load 32 bit vsts.

Yes, but only into a 32-bit process. The big DAWs work around this by shipping two plugin hosts.

Of course I'm well aware that 32-bit is almost dead and wouldn't suggest shipping 32-bit releases. But unless it causes extra effort there's no harm in letting tinkerers decide for themselves what's useful. Build issues, e.g. with Python, can just as easily occur when building for 64-bit, but IME the experience is basically perfect. I have both a 32-bit and a 64-bit Python installed, and CMake reliably detects the right one.

**Comment by baconpaul** [comment]
Ha yeah sure. So my problem was I didn't have 32 bit python installed and was doing an accidental 32 bit build so added a warning. Then figured why not just make it fatal. 

At least now we show the bittiness at build time so I would have caught it. 

And agree 32 bit windows should die. I'm thinking about no longer shipping a 32 bit surge binary with our next release since our downloads are just so few.

**Comment by mvf** [comment]
Gotcha. Yeah, the bitness CMake message brought some much-needed clarity, also very useful in cross builds. Totally agree that shipping 32-bit Surge XT is not worth the effort, all the more since we're not a plugin host.

Gotta say though, when debugging this 32-bit Windows stuff, the short pointers were really pleasant. I might switch back to 32-bit for my Windows work. :sweat_smile:

**Pull request merged**
