### PR TITLE
Improve Linux build scripts

### PR DESCRIPTION
**Pull request by 4oo4**
I set this to bash for now, but it can always be changed to sh later. I wasn't sure about the MacOS shell scripts, but you could do the same thing there (if `env` works the same way?) or change these to `#!/bin/sh` to match, even though I think using `env` is best practice for Linux.

### CODE REVIEW

**Comment by dromer** [comment]
If you're going to fix these files then maybe also make sure there are newlines at the end of them.

(although honestly the whole build system could use a revamp to be more modern and robust. TBD)

**Comment by 4oo4** [comment]
Done, good catch. Agreed that the build system could be a lot better (I think what it really needs is CI), but this should at least make it a tiny bit better for now.

**Comment by baconpaul** [comment]
Hi linxuers! Comments and help on #187 appreciated if you want.

**Comment by dromer** [comment]
Wow, awesome work @baconpaul !

I'll try your build right away!

**Comment by 4oo4** [comment]
Awesome, that's a way better solution so I'm closing this.

**Pull request closed without merging**
